name: Coverage

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.24.x]

    name: go-coverage
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v5
      - name: Check test coverage
        run: make test-coverage
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
