name: Coverage

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
permissions:
  contents: read

jobs:
  test:
    name: go-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.x
      - uses: actions/checkout@v7
      - name: Check test coverage
        run: |
          go test -short -coverprofile cover.out -covermode=atomic -gcflags '-N -l' $(go list ./pkg/... | grep -v testutils)
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
