name: Lint

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.24.x]

    name: golangci-lint
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
